// File: lib/content.js
// Description: Contains all multilingual text, icons, and available components for the application.

import {
    ChatBubbleBottomCenterTextIcon,
    ClockIcon,
    Cog8ToothIcon,
    EnvelopeIcon,
    FolderIcon,
    QuestionMarkCircleIcon,
    ShoppingCartIcon,
    Squares2X2Icon,
    StarIcon,
    UserCircleIcon,
    UsersIcon, WrenchScrewdriverIcon
} from '@heroicons/react/24/outline';

const content = {
    id: {
        tagline: 'Jelaskan website impianmu. Kami yang akan mewujudkannya menjadi kenyataan.',
        companyNameLabel: 'Nama Perusahaan / Personal Brand',
        companyNamePlaceholder: 'Contoh: Kopi Kenangan, Raditya Dika',
        logoLabel: 'Logo',
        logoUrlLabel: 'Atau URL Logo',
        logoUrlPlaceholder: 'https://contoh.com/logo.png',
        websiteTypeLabel: 'Jenis Website',
        websiteTypeOptions: ['Toko Online', 'Portfolio Kreatif', 'Blog Pribadi', 'Profil Perusahaan'],
        aboutTextLabel: 'Deskripsi Singkat (Tentang Brand Anda)',
        aboutTextPlaceholder: 'Jelaskan secara singkat tentang brand atau diri Anda...',
        contactEmailLabel: 'Email Kontak Utama',
        contactEmailPlaceholder: 'email@bisniskamu.com',
        
        designSpecLabel: 'Spesifikasi Desain & Struktur',
        pageBuilderLabel: 'Pembangun Halaman',
        addPage: 'Tambah Halaman Baru',
        pageLabel: 'Halaman',
        slugLabel: 'URL Slug',
        slugPlaceholder: '/tentang-kami',
        selectComponentLabel: 'Pilih Komponen untuk ditambahkan',
        addComponent: 'Tambah Komponen',

        colorPaletteLabel: 'Palet Warna',
        addColor: 'Tambah Warna',
        fontLabel: 'Pilih Font',
        animationLabel: 'Gunakan Animasi Halus',
        
        featuresLabel: 'Isi Konten Fitur',
        featureMapping: {
            'Toko Online': { productList: { name: "Katalog Produk", icon: <ShoppingCartIcon className="w-6 h-6" /> }, featuredProduct: { name: "Produk Unggulan", icon: <StarIcon className="w-6 h-6" /> }, testimonials: { name: "Testimonial Pelanggan", icon: <ChatBubbleBottomCenterTextIcon className="w-6 h-6" /> } },
            'Portfolio Kreatif': { projectGallery: { name: "Galeri Proyek", icon: <Squares2X2Icon className="w-6 h-6" /> }, aboutMe: { name: "Profil Detail", icon: <UserCircleIcon className="w-6 h-6" /> }, process: { name: "Proses Kerja", icon: <Cog8ToothIcon className="w-6 h-6" /> } },
            'Blog Pribadi': { postCategories: { name: "Kategori Tulisan", icon: <FolderIcon className="w-6 h-6" /> }, newsletter: { name: "Form Newsletter", icon: <EnvelopeIcon className="w-6 h-6" /> }, recentPosts: { name: "Postingan Terbaru", icon: <ClockIcon className="w-6 h-6" /> } },
            'Profil Perusahaan': { ourTeam: { name: "Profil Tim", icon: <UsersIcon className="w-6 h-6" /> }, services: { name: "Daftar Layanan", icon: <WrenchScrewdriverIcon className="w-6 h-6" /> }, faq: { name: "Tanya Jawab (FAQ)", icon: <QuestionMarkCircleIcon className="w-6 h-6" /> } }
        },
        
        availableComponents: [
            { id: 'hero', name: 'Hero (Judul Utama & Gambar)' },
            { id: 'about', name: 'Tentang Kami (dari Deskripsi)' },
            { id: 'contact', name: 'Formulir Kontak' },
            { id: 'gallery', name: 'Galeri Proyek' },
            { id: 'products', name: 'Katalog Produk' },
            { id: 'testimonials', name: 'Testimonial' },
            { id: 'team', name: 'Tim Kami' },
            { id: 'services', name: 'Layanan Kami' },
            { id: 'faq', name: 'FAQ' },
            { id: 'textBlock', name: 'Blok Teks Kustom' },
            { id: 'newsletter', name: 'Form Newsletter' },
            { id: 'recentPosts', name: 'Tampilan Postingan Blog' },
        ],
        
        componentMapping: {
            'Toko Online': ['hero', 'about', 'products', 'testimonials', 'contact', 'faq'],
            'Portfolio Kreatif': ['hero', 'about', 'gallery', 'contact'],
            'Blog Pribadi': ['hero', 'about', 'recentPosts', 'newsletter', 'contact'],
            'Profil Perusahaan': ['hero', 'about', 'services', 'team', 'contact', 'faq'],
        },
        
        productListLabel: 'Detail Produk',
        productNameLabel: "Nama Produk",
        priceLabel: "Harga",
        oldPriceLabel: "Harga Lama (Opsional)",
        addProduct: "Tambah Produk",
        projectGalleryLabel: 'Detail Proyek Portfolio',
        projectNameLabel: "Nama Proyek",
        projectDescLabel: "Deskripsi Singkat Proyek",
        projectUrlLabel: "URL Proyek (Live)",
        addProject: 'Tambah Proyek',
        testimonialsLabel: 'Testimonial Pelanggan',
        customerNameLabel: 'Nama Pelanggan',
        testimonialTextLabel: 'Isi Testimoni',
        customerPhotoLabel: 'Foto Pelanggan',
        addTestimonial: 'Tambah Testimoni',
        ourTeamLabel: 'Anggota Tim',
        memberNameLabel: 'Nama Anggota Tim',
        memberRoleLabel: 'Posisi / Jabatan',
        memberPhotoLabel: 'Foto Anggota Tim',
        addMember: 'Tambah Anggota Tim',
        servicesLabel: 'Layanan yang Ditawarkan',
        serviceNameLabel: 'Nama Layanan',
        serviceDescLabel: 'Deskripsi Layanan',
        addService: 'Tambah Layanan',
        faqLabel: 'Tanya Jawab (FAQ)',
        questionLabel: 'Pertanyaan',
        answerLabel: 'Jawaban',
        addFaq: 'Tambah FAQ',
        postCategoriesLabel: 'Kategori Tulisan (pisahkan dengan koma)',
        processLabel: 'Proses Kerja',
        detailedAboutMeLabel: 'Tentang Saya (Detail)',
        customParamsLabel: 'Parameter Tambahan',
        customParamsPlaceholderKey: 'Nama Parameter',
        customParamsPlaceholderValue: 'Nilai Parameter',
        customParamsExample: 'Contoh: `Target Audiens` = `Anak Muda`',
        addParam: 'Tambah Parameter',
        submitButton: 'Buatkan Saya Website!',
        loadingButton: 'Mengirim...',
        errorMsg: 'Gagal submit. Mohon coba lagi.',
        successTitle: 'Berhasil Submit!',
        successSubtitle: 'Data Anda telah kami terima. Kami akan segera membuatkan website impianmu! Perkiraan waktu pengerjaan 30-60 menit setelah pembayaran.',
        paymentTitle: 'Informasi Pembayaran',
        paymentSubtitle: 'Silakan lakukan pembayaran sebesar',
        paymentAmount: 'Rp 150.000',
        paymentStart: 'untuk memulai proses pembuatan website.',
        bankTransfer: 'Bank Transfer',
        qrisSupport: 'Mendukung semua E-Wallet & M-Banking',
        paymentConfirmation: 'Setelah pembayaran, mohon konfirmasi melalui WhatsApp ke nomor',
        summaryTitle: 'Ringkasan Permintaan Anda',
    },
    en: {
        tagline: 'Describe your dream website. We will make it a reality.',
        companyNameLabel: 'Company Name / Personal Brand',
        companyNamePlaceholder: 'Example: The Coffee Bean, John Doe',
        logoLabel: 'Logo',
        logoUrlLabel: 'Or Logo URL',
        logoUrlPlaceholder: 'https://example.com/logo.png',
        websiteTypeLabel: 'Website Type',
        websiteTypeOptions: ['E-commerce Store', 'Creative Portfolio', 'Personal Blog', 'Company Profile'],
        aboutTextLabel: 'Brief Description (About Your Brand)',
        aboutTextPlaceholder: 'Briefly describe your brand or yourself...',
        contactEmailLabel: 'Main Contact Email',
        contactEmailPlaceholder: 'your@email.com',
        
        designSpecLabel: 'Design & Structure Specifications',
        pageBuilderLabel: 'Page Builder',
        addPage: 'Add New Page',
        pageLabel: 'Page',
        slugLabel: 'URL Slug',
        slugPlaceholder: '/about-us',
        selectComponentLabel: 'Select a component to add',
        addComponent: 'Add Component',

        colorPaletteLabel: 'Color Palette',
        addColor: 'Add Color',
        fontLabel: 'Choose a Font',
        animationLabel: 'Use Subtle Animations',
        
        featuresLabel: 'Fill Feature Content',
        featureMapping: {
            'E-commerce Store': { productList: { name: "Product Catalog", icon: <ShoppingCartIcon className="w-6 h-6" /> }, featuredProduct: { name: "Featured Products", icon: <StarIcon className="w-6 h-6" /> }, testimonials: { name: "Customer Testimonials", icon: <ChatBubbleBottomCenterTextIcon className="w-6 h-6" /> } },
            'Creative Portfolio': { projectGallery: { name: "Project Gallery", icon: <Squares2X2Icon className="w-6 h-6" /> }, aboutMe: { name: "Detailed Profile", icon: <UserCircleIcon className="w-6 h-6" /> }, process: { name: "Work Process", icon: <Cog8ToothIcon className="w-6 h-6" /> } },
            'Personal Blog': { postCategories: { name: "Post Categories", icon: <FolderIcon className="w-6 h-6" /> }, newsletter: { name: "Newsletter Form", icon: <EnvelopeIcon className="w-6 h-6" /> }, recentPosts: { name: "Recent Posts", icon: <ClockIcon className="w-6 h-6" /> } },
            'Company Profile': { ourTeam: { name: "Team Profiles", icon: <UsersIcon className="w-6 h-6" /> }, services: { name: "Service List", icon: <WrenchScrewdriverIcon className="w-6 h-6" /> }, faq: { name: "FAQ Section", icon: <QuestionMarkCircleIcon className="w-6 h-6" /> } }
        },
        
        availableComponents: [
            { id: 'hero', name: 'Hero Section (Large Image & Title)' },
            { id: 'about', name: 'About Us (from Brief Description)' },
            { id: 'contact', name: 'Contact Form' },
            { id: 'gallery', name: 'Project Gallery' },
            { id: 'products', name: 'Product Catalog' },
            { id: 'testimonials', name: 'Testimonials' },
            { id: 'team', name: 'Our Team' },
            { id: 'services', name: 'Our Services' },
            { id: 'faq', name: 'FAQ' },
            { id: 'textBlock', name: 'Custom Text Block' },
            { id: 'newsletter', name: 'Newsletter Form' },
            { id: 'recentPosts', name: 'Recent Blog Posts' },
        ],
        
        componentMapping: {
            'E-commerce Store': ['hero', 'about', 'products', 'testimonials', 'contact', 'faq'],
            'Creative Portfolio': ['hero', 'about', 'gallery', 'contact'],
            'Personal Blog': ['hero', 'about', 'recentPosts', 'newsletter', 'contact'],
            'Company Profile': ['hero', 'about', 'services', 'team', 'contact', 'faq'],
        },
        
        productListLabel: 'Product Details',
        productNameLabel: "Product Name",
        priceLabel: "Price",
        oldPriceLabel: "Old Price (Optional)",
        addProduct: "Add Product",
        projectGalleryLabel: 'Portfolio Project Details',
        projectNameLabel: "Project Name",
        projectDescLabel: "Brief Project Description",
        projectUrlLabel: "Live Project URL",
        addProject: 'Add Project',
        testimonialsLabel: 'Customer Testimonials',
        customerNameLabel: 'Customer Name',
        testimonialTextLabel: 'Testimonial Text',
        customerPhotoLabel: 'Customer Photo',
        addTestimonial: 'Add Testimonial',
        ourTeamLabel: 'Team Members',
        memberNameLabel: 'Team Member Name',
        memberRoleLabel: 'Position / Role',
        memberPhotoLabel: 'Team Member Photo',
        addMember: 'Add Team Member',
        servicesLabel: 'Services Offered',
        serviceNameLabel: 'Service Name',
        serviceDescLabel: 'Service Description',
        addService: 'Add Service',
        faqLabel: 'Frequently Asked Questions (FAQ)',
        questionLabel: 'Question',
        answerLabel: 'Answer',
        addFaq: 'Add FAQ',
        postCategoriesLabel: 'Post Categories (comma-separated)',
        processLabel: 'Work Process',
        detailedAboutMeLabel: 'About Me (Detailed)',
        customParamsLabel: 'Additional Parameters',
        customParamsPlaceholderKey: 'Parameter Name',
        customParamsPlaceholderValue: 'Parameter Value',
        customParamsExample: 'Example: `Target Audience` = `Young Adults`',
        addParam: 'Add Parameter',
        submitButton: 'Build My Website!',
        loadingButton: 'Submitting...',
        errorMsg: 'Submission failed. Please try again.',
        successTitle: 'Submission Successful!',
        successSubtitle: 'Your data has been received. We will start building your dream website shortly! Estimated time is 30-60 minutes after payment.',
        paymentTitle: 'Payment Information',
        paymentSubtitle: 'Please make a payment of',
        paymentAmount: '$15 USD',
        paymentStart: 'to begin the website creation process.',
        bankTransfer: 'Bank Transfer',
        qrisSupport: 'Supports all E-Wallets & M-Banking',
        paymentConfirmation: 'After payment, please confirm via WhatsApp to',
        summaryTitle: 'Your Request Summary',
    }
};

export default content;
